# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.BesselTab = QtWidgets.QWidget()
        self.BesselTab.setObjectName("BesselTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BesselTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.besselGraphFrame = QtWidgets.QFrame(self.BesselTab)
        self.besselGraphFrame.setObjectName("besselGraphFrame")
        self.besselGraphLayout = QtWidgets.QHBoxLayout(self.besselGraphFrame)
        self.besselGraphLayout.setObjectName("besselGraphLayout")
        self.horizontalLayout.addWidget(self.besselGraphFrame)
        self.besselControlsFrame = QtWidgets.QFrame(self.BesselTab)
        self.besselControlsFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.besselControlsFrame.setMaximumSize(QtCore.QSize(200, 10000))
        self.besselControlsFrame.setObjectName("besselControlsFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.besselControlsFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.besselInfoLabel = QtWidgets.QLabel(self.besselControlsFrame)
        self.besselInfoLabel.setObjectName("besselInfoLabel")
        self.verticalLayout_3.addWidget(self.besselInfoLabel)
        self.besselResultsEdit = QtWidgets.QTextEdit(self.besselControlsFrame)
        self.besselResultsEdit.setObjectName("besselResultsEdit")
        self.verticalLayout_3.addWidget(self.besselResultsEdit)
        self.besselPlotButton = QtWidgets.QPushButton(self.besselControlsFrame)
        self.besselPlotButton.setObjectName("besselPlotButton")
        self.verticalLayout_3.addWidget(self.besselPlotButton)
        self.horizontalLayout.addWidget(self.besselControlsFrame)
        self.tabWidget.addTab(self.BesselTab, "")
        self.speedsTab = QtWidgets.QWidget()
        self.speedsTab.setObjectName("speedsTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.speedsTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.speedsFrame = QtWidgets.QFrame(self.speedsTab)
        self.speedsFrame.setObjectName("speedsFrame")
        self.speedsGraphLayout = QtWidgets.QVBoxLayout(self.speedsFrame)
        self.speedsGraphLayout.setObjectName("speedsGraphLayout")
        self.verticalLayout_4.addWidget(self.speedsFrame)
        self.speedsControlFrame = QtWidgets.QFrame(self.speedsTab)
        self.speedsControlFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.speedsControlFrame.setObjectName("speedsControlFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.speedsControlFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.speedsPlotButton = QtWidgets.QPushButton(self.speedsControlFrame)
        self.speedsPlotButton.setObjectName("speedsPlotButton")
        self.horizontalLayout_3.addWidget(self.speedsPlotButton)
        self.verticalLayout_4.addWidget(self.speedsControlFrame)
        self.tabWidget.addTab(self.speedsTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.paramsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.paramsGroupBox.setMaximumSize(QtCore.QSize(16777215, 160))
        self.paramsGroupBox.setObjectName("paramsGroupBox")
        self.paramsLayout = QtWidgets.QVBoxLayout(self.paramsGroupBox)
        self.paramsLayout.setObjectName("paramsLayout")
        self.label = QtWidgets.QLabel(self.paramsGroupBox)
        self.label.setObjectName("label")
        self.paramsLayout.addWidget(self.label)
        self.radiusEdit = QtWidgets.QLineEdit(self.paramsGroupBox)
        self.radiusEdit.setObjectName("radiusEdit")
        self.paramsLayout.addWidget(self.radiusEdit)
        self.label_2 = QtWidgets.QLabel(self.paramsGroupBox)
        self.label_2.setObjectName("label_2")
        self.paramsLayout.addWidget(self.label_2)
        self.epsEdit = QtWidgets.QLineEdit(self.paramsGroupBox)
        self.epsEdit.setObjectName("epsEdit")
        self.paramsLayout.addWidget(self.epsEdit)
        self.horizontalLayout_2.addWidget(self.paramsGroupBox)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.coefEdit = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.coefEdit.setObjectName("coefEdit")
        self.verticalLayout.addWidget(self.coefEdit)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 553, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.besselInfoLabel.setText(_translate("MainWindow", "Результаты:"))
        self.besselPlotButton.setText(_translate("MainWindow", "Построить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BesselTab), _translate("MainWindow", "Функция Бесселя"))
        self.speedsPlotButton.setText(_translate("MainWindow", "Построить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.speedsTab), _translate("MainWindow", "Графики скоростей"))
        self.paramsGroupBox.setTitle(_translate("MainWindow", "Параметры волновода"))
        self.label.setText(_translate("MainWindow", "R"))
        self.radiusEdit.setText(_translate("MainWindow", "0.0092"))
        self.label_2.setText(_translate("MainWindow", "ε"))
        self.epsEdit.setText(_translate("MainWindow", "7.1"))
        self.verticalGroupBox.setTitle(_translate("MainWindow", "Параметры перебора частот"))
        self.label_3.setText(_translate("MainWindow", "ω=2π*10^9*k"))
        self.label_4.setText(_translate("MainWindow", "k"))
        self.coefEdit.setText(_translate("MainWindow", "70"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

